### ISSUE TITLE
1024.Cool technical writing

### ISSUE THREAD

**Issue by martinageradams** [martinageradams/blog#4]
## Reason of activity

-[How to find remote job opportunities abroad through English writing](https://eleduck.com/posts/PJpfOm)

After reading this post from Dianya Community, my heart was overwhelmed. Not everyone is suitable for [remote work](https://eleduck.com), but the opportunity to find a [remote work](https://eleduck.com) through English technical writing is far away for many programming partners And things.

How can we approach the status of the article author? I want to ask you a few questions.

-**Do you insist on writing? **
-**Do you insist on writing in English? **
-**Do you insist on English technical writing? **
-**Do you want to be stronger? Improve technical experience and update one's own experience**
-**You raised the above four questions, have you acted for it? **

The above question essentially means that on the path of personal growth, we need to cultivate a good habit of long-term persistence and positive motivation.

Do you have such a habit? the answer is negative. Many small partners have set up and set up flags, and have not persisted to the end.

**We care about our own personal development and technological accumulation, and want to put into practice a long-term adherence to good habits. ** This is the real idea of ​​many friends who want to join the "[1024.Cool](https://1024.Cool)" community technical writing check-in activity.

## Activity purpose

-The emphasis is on **writing**, followed by **English writing**, **technical writing**, and finally **English technical writing**.
-Action is the first step! Those who travel a hundred miles are half and ninety, **please act immediately**.
-**When asking a question, please also attach your solution**. Only in this way can we promote effective two-way communication.
-Do not welcome or recommend any **meaningless chat**.
-Encourage ** sincere and friendly** to express your thoughts. We are all friends and hope to get along as good friends, good sisters, and help each other.
-Don't begrudge the **appreciation** of others.

## rule of activity

-Participants need to share an original article to the writing team every three weeks
-Small partners who have not shared an original share in three weeks will be cleared
-In special circumstances, it is indeed impossible to complete an original article within three weeks, please report to the group @老王报备
-Friends who are willing to submit original articles to the "Frontend Time and Space" community official account, please @有赫 or @老王. Hope to submit the original manuscript, or you can submit the manuscript in the form of reprinting on the official account.

## Recommended tools
-MarkDown-the writing style that programmers must know.
-Yuque —— Create a personal knowledge warehouse.
-Evernote-your second brain.
-Gmial —— Excellent physical examination for use of mailbox.
-Github-Gayhub that programmers know.

## Number of activities

Adopt the small-scale strategy of special forces, small but beautiful, and exquisite communication. At present, 11 people have participated in the event.

## Activity time

April 23, 2020 to April 23, 2021

The second phase will start on April 24, 2021

## Reference
-[Talk about some experiences, thoughts, and plans of the Ducky community](https://eleduck.com/posts/MZXfoe)
-[How to find remote job opportunities abroad through English writing](https://eleduck.com/posts/PJpfOm)

**Comment by tangdou369098655** [comment]
Can I join part way through ?  I want to step up my English level, but it's too tough.

**Comment by belle-sketch** [comment]
How can I join this writing group？

**Comment by martinageradams** [comment]
> How can I join this writing group？

vx: martinageradams
